name:
  host: gateway
spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
         - id: ux-channel-user-authorization
           uri: lb://ux-channel-user-authorization
           predicates:
           - Path=/user/**
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true    
  instance:
    hostname: localhost