spring:  
  eureka:
    instance:
      hostname: localhost
      statusPageUrl: http://${eureka.instance.hostname}/info
      healthCheckUrl: http://${eureka.instance.hostname}/health
      homePageUrl: http://${eureka.instance.hostname}/  
    client:   
      fetch-registry: false
      register-with-eureka: true
      healthcheck: 
        enable: true
      service-url:
        default-zone: http://${eureka.instance.hostname}:${server.port}/eureka  