name:
  host: confirations
eureka:
  client:
    service-url:
      defaultZone: http://10.0.2.15:8761/eureka/
    fetch-registry: true
    register-with-eureka: true    
  instance:
    hostname: 10.0.2.15