name:
  host: registry
spring:  
  eureka:
    instance:
      hostname: localhost
      statusPageUrl: https://${eureka.hostname}/info
      healthCheckUrl: https://${eureka.hostname}/health
      homePageUrl: https://${eureka.hostname}/  
    client:   
      fetch-registry: false
      register-with-eureka: true
      healthcheck: 
        enable: true
      service-url:
        default-zone: http://${eureka.instance.hostname}:${server.port}/eureka